language: android
jdk: oraclejdk8
os: linux
sudo: required

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-28
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'

# Accept license
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-28"
  - ./gradlew dependencies || true

script: ./gradlew build --stacktrace
